USE [master]
GO

/****** Object:  Database [EmployeePayroll]    Script Date: 10-02-2025 21:17:43 ******/
CREATE DATABASE [EmployeePayroll]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EmployeePayroll', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS2019\MSSQL\DATA\EmployeePayroll.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EmployeePayroll_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS2019\MSSQL\DATA\EmployeePayroll_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EmployeePayroll].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EmployeePayroll] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EmployeePayroll] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EmployeePayroll] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EmployeePayroll] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EmployeePayroll] SET ARITHABORT OFF 
GO

ALTER DATABASE [EmployeePayroll] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [EmployeePayroll] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EmployeePayroll] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EmployeePayroll] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EmployeePayroll] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EmployeePayroll] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EmployeePayroll] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EmployeePayroll] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EmployeePayroll] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EmployeePayroll] SET  DISABLE_BROKER 
GO

ALTER DATABASE [EmployeePayroll] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EmployeePayroll] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EmployeePayroll] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EmployeePayroll] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EmployeePayroll] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EmployeePayroll] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EmployeePayroll] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EmployeePayroll] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [EmployeePayroll] SET  MULTI_USER 
GO

ALTER DATABASE [EmployeePayroll] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EmployeePayroll] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EmployeePayroll] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [EmployeePayroll] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [EmployeePayroll] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [EmployeePayroll] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [EmployeePayroll] SET QUERY_STORE = OFF
GO

ALTER DATABASE [EmployeePayroll] SET  READ_WRITE 
GO


